### ISSUE TITLE
Should HipChatPS continue to support PowerShell version 2?

### ISSUE THREAD

**Issue by markwragg** [AtlassianPS/HipChatPS#2]
When I wrote this module originally I was working in an environment where I needed it to be usable on systems that had PowerShell version 2 installed. As a result the module includes Private\ConvertTo-Json and falls back to .NET methods for web requests where `Invoke-WebRequest` is not available. It only uses this code when PS version is 2.

Should the module continue to support PS v2 (which might become increasingly complex as more functions are added) or should we now just assume a minimum supported PS version of 3 and remove these pieces from Send-HipChat?

**Comment by lipkau** [comment]
I would rather not. All OS versions that Microsoft still supports include v3+

**Comment by markwragg** [comment]
I agree. I'll leave it in the initial commit and then i'll remove it in the next version.
